# syntax=docker/dockerfile:1
ARG NODE_BASE_IMAGE=node:24-bookworm-slim
ARG PNPM_VERSION=10.33.0
ARG DEBIAN_MIRROR_HOST=mirrors.ustc.edu.cn
ARG NPM_REGISTRY=https://registry.npmmirror.com

FROM ${NODE_BASE_IMAGE}

ARG PNPM_VERSION
ARG DEBIAN_MIRROR_HOST
ARG NPM_REGISTRY

ENV COREPACK_NPM_REGISTRY=${NPM_REGISTRY}
ENV NPM_CONFIG_REGISTRY=${NPM_REGISTRY}

RUN if [ -f /etc/apt/sources.list.d/debian.sources ]; then \
    sed -i "s#http://deb.debian.org/debian#http://${DEBIAN_MIRROR_HOST}/debian#g" /etc/apt/sources.list.d/debian.sources \
    && sed -i "s#http://deb.debian.org/debian-security#http://${DEBIAN_MIRROR_HOST}/debian-security#g" /etc/apt/sources.list.d/debian.sources; \
  elif [ -f /etc/apt/sources.list ]; then \
    sed -i "s#http://deb.debian.org/debian#http://${DEBIAN_MIRROR_HOST}/debian#g" /etc/apt/sources.list \
    && sed -i "s#http://deb.debian.org/debian-security#http://${DEBIAN_MIRROR_HOST}/debian-security#g" /etc/apt/sources.list; \
  fi \
  && apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates curl git g++ make python3 tar xz-utils zstd \
  && rm -rf /var/lib/apt/lists/* \
  && corepack enable \
  && corepack prepare pnpm@${PNPM_VERSION} --activate
